question_data = [
    {"type":"boolean",
     "difficulty":"medium",
     "category":"Science: Computers",
     "question":"Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
     "correct_answer":"False",
     "incorrect_answers":["True"]},
    {"type":"boolean",
    "difficulty":"easy",
    "category":"Science: Computers",
    "question":"Pointers were not used in the original C programming language; they were added later on in C++.",
    "correct_answer":"False",
    "incorrect_answers":["True"]},
    {"type":"boolean",
    "difficulty":"easy",
    "category":"Science: Computers",
    "question":"The Windows 7 operating system has six main editions.",
    "correct_answer":"True",
    "incorrect_answers":["False"]},
    {"type":"boolean",
    "difficulty":"hard",
    "category":"Science: Computers",
    "question":"DHCP stands for Dynamic Host Configuration Port.",
    "correct_answer":"False",
    "incorrect_answers":["True"]},
    {"type":"boolean",
    "difficulty":"hard",
    "category":"Science: Computers",
    "question":"The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
    "correct_answer":"False",
    "incorrect_answers":["True"]},
    {"type":"boolean",
    "difficulty":"hard",
    "category":"Science: Computers",
    "question":"The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
    "correct_answer":"True",
    "incorrect_answers":["False"]},
    {"type":"boolean",
     "difficulty":"medium",
     "category":"Science: Computers",
     "question":"A Boolean value of &quot;0&quot; represents which of these words?",
     "correct_answer":"False",
     "incorrect_answers":["True"]},
    {"type":"boolean",
      "difficulty":"medium",
      "category":"Science: Computers",
      "question":"It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
      "correct_answer":"True",
      "incorrect_answers":["False"]},
    {"type":"boolean",
     "difficulty":"easy",
     "category":"Science: Computers",
     "question":"RAM stands for Random Access Memory.",
    "correct_answer":"True","incorrect_answers":["False"]},
             {"type":"boolean",
              "difficulty":"medium",
              "category":"Science: Computers",
              "question":"To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
              "correct_answer":"True",
              "incorrect_answers":["False"]},
              {"type":"boolean",
               "difficulty":"medium",
               "category":"Science: Mathematics",
               "question":"Zero factorial is equal to zero. ",
               "correct_answer":"False",
               "incorrect_answers":["True"]},
               {"type":"boolean",
                "difficulty":"medium",
                "category":"Science: Mathematics",
                "question":"The set of all algebraic numbers is countable.",
                "correct_answer":"True",
                "incorrect_answers":["False"]},
                {"type":"boolean",
                 "difficulty":"easy",
                 "category":"Science: Mathematics",
                 "question":"A scalene triangle has two sides of equal length.",
                 "correct_answer":"False",
                 "incorrect_answers":["True"]},
                 {"type":"boolean",
                  "difficulty":"medium",
                  "category":"Science: Mathematics",
                  "question":"A &#039;Millinillion&#039; is a real number.",
                  "correct_answer":"True",
                  "incorrect_answers":["False"]},
                  {"type":"boolean",
                   "difficulty":"hard",
                   "category":"Science: Mathematics",
                   "question":"L&#039;H&ocirc;pital was the mathematician who created the homonymous rule that uses derivatives to evaluate limits with indeterminations.",
                   "correct_answer":"False",
                   "incorrect_answers":["True"]},
                   {"type":"boolean",
                    "difficulty":"easy",
                    "category":"Science: Mathematics",
                    "question":"A universal set, or a set that contains all sets, exists.",
                    "correct_answer":"False",
                    "incorrect_answers":["True"]},
   {"type":"boolean",
   "difficulty":"hard",
   "category":"Science: Mathematics",
   "question":"The binary number &quot;101001101&quot; is equivalent to the Decimal number &quot;334&quot;",
   "correct_answer":"False",
   "incorrect_answers":["True"]},
   {"type":"boolean",
    "difficulty":"easy",
    "category":"Science: Mathematics",
    "question":"An equilateral triangle always has every angle measuring 60&deg;.",
    "correct_answer":"True",
    "incorrect_answers":["False"]},
    {"type":"boolean",
    "difficulty":"easy",
    "category":"Science: Mathematics",
    "question":"The &#039;Squaring the Circle&#039; problem is solvable.",
    "correct_answer":"False",
    "incorrect_answers":["True"]},
    {"type":"boolean",
    "difficulty":"easy",
    "category":"Science: Mathematics",
    "question":"An isosceles triangle has two sides of equal length as opposed to three.",
    "correct_answer":"True",
    "incorrect_answers":["False"]}
]
